version: "3.7"

services:
  ##############################
  # Backend Container
  ##############################
  server:
    container_name: server
    restart: always
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "server"
    ports:
      - "4000:4000"

# Client Container
  ##############################
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "client"
    restart: always
    container_name: "client"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
